import { BoardType } from '../../types/board';
import { PuzzleDef } from '../../types/puzzle';

export const PUZZLE_CATALOG: PuzzleDef[] = [
  {
    id: 'puz-1',
    title: 'Nivel 1: Jaque Mate en 1',
    subtitle: 'Tres en Raya 3x3 Clásico',
    difficulty: 'easy',
    boardType: BoardType.TicTacToe3x3,
    playerSymbol: 'X',
    initialMoves: [
      { pos: { x: 0, y: 0, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 1, y: 0, z: 0, w: 0 }, symbol: 'O' },
      { pos: { x: 0, y: 1, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 1, y: 1, z: 0, w: 0 }, symbol: 'O' },
    ],
    targetMove: { x: 0, y: 2, z: 0, w: 0 },
    explanation: '¡Fila superior completada! (0,0)-(0,1)-(0,2) asegura la victoria instantánea.',
  },
  {
    id: 'puz-2',
    title: 'Nivel 2: La Horquilla Mortal',
    subtitle: 'Creación de Doble Amenaza',
    difficulty: 'easy',
    boardType: BoardType.TicTacToe3x3,
    playerSymbol: 'X',
    initialMoves: [
      { pos: { x: 0, y: 0, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 1, y: 1, z: 0, w: 0 }, symbol: 'O' },
      { pos: { x: 2, y: 2, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 0, y: 2, z: 0, w: 0 }, symbol: 'O' },
    ],
    targetMove: { x: 2, y: 0, z: 0, w: 0 },
    explanation: 'Al jugar (2,0), creas una doble amenaza simultánea en la columna 0 y en la fila 2 que O no puede parar.',
  },
  {
    id: 'puz-3',
    title: 'Nivel 3: Bloqueo y Contragolpe',
    subtitle: 'Defensa activa con victoria',
    difficulty: 'medium',
    boardType: BoardType.TicTacToe3x3,
    playerSymbol: 'O',
    initialMoves: [
      { pos: { x: 0, y: 0, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 1, y: 1, z: 0, w: 0 }, symbol: 'O' },
      { pos: { x: 0, y: 1, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 2, y: 1, z: 0, w: 0 }, symbol: 'O' },
      { pos: { x: 2, y: 0, z: 0, w: 0 }, symbol: 'X' },
    ],
    targetMove: { x: 0, y: 2, z: 0, w: 0 },
    explanation: 'Bloqueas la amenaza letal de X en fila 0 y mantienes el control de la partida.',
  },
  {
    id: 'puz-4',
    title: 'Nivel 4: Esquivar la Piedra',
    subtitle: '4x4 con Obstáculos',
    difficulty: 'medium',
    boardType: BoardType.Obstacles4x4,
    playerSymbol: 'X',
    initialMoves: [
      { pos: { x: 1, y: 0, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 2, y: 0, z: 0, w: 0 }, symbol: 'O' },
      { pos: { x: 1, y: 1, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 2, y: 1, z: 0, w: 0 }, symbol: 'O' },
      { pos: { x: 1, y: 2, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 2, y: 2, z: 0, w: 0 }, symbol: 'O' },
    ],
    targetMove: { x: 1, y: 3, z: 0, w: 0 },
    explanation: '¡Completas la fila 1 limpia de 4 en raya evitando las esquinas bloqueadas!',
  },
  {
    id: 'puz-5',
    title: 'Nivel 5: Trampa en Misère',
    subtitle: 'Variante Inversa 3x3',
    difficulty: 'hard',
    boardType: BoardType.Misere3x3,
    playerSymbol: 'X',
    initialMoves: [
      { pos: { x: 0, y: 0, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 1, y: 1, z: 0, w: 0 }, symbol: 'O' },
      { pos: { x: 2, y: 2, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 0, y: 2, z: 0, w: 0 }, symbol: 'O' },
      { pos: { x: 2, y: 0, z: 0, w: 0 }, symbol: 'O' },
    ],
    targetMove: { x: 0, y: 1, z: 0, w: 0 },
    explanation: 'En Misère, colocar en (0,1) no forma 3 en raya para X y deja a O con opciones obligadas que le harán perder.',
  },
  {
    id: 'puz-6',
    title: 'Nivel 6: Desplazamiento Mortal',
    subtitle: 'Modo Movimiento',
    difficulty: 'hard',
    boardType: BoardType.Movement3x3,
    playerSymbol: 'X',
    initialMoves: [
      { pos: { x: 0, y: 0, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 1, y: 0, z: 0, w: 0 }, symbol: 'O' },
      { pos: { x: 0, y: 1, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 1, y: 1, z: 0, w: 0 }, symbol: 'O' },
      { pos: { x: 1, y: 2, z: 0, w: 0 }, symbol: 'X' },
      { pos: { x: 2, y: 0, z: 0, w: 0 }, symbol: 'O' },
    ],
    targetMove: { x: 0, y: 2, z: 0, w: 0 },
    explanation: 'Al deslizar X de (1,2) a la casilla adyacente (0,2), ¡completas la fila superior para la victoria!',
  },
];
